# Generated by Django 5.0.6 on 2024-06-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_img', models.ImageField(upload_to='original_img')),
                ('compressed_img', models.ImageField(upload_to='compressed_img')),
                ('compression_quality', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)])),
                ('compressed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
