# Generated by Django 5.0.6 on 2024-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_compression', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecompression',
            name='compressed_img',
            field=models.ImageField(upload_to='compressed_img/'),
        ),
        migrations.AlterField(
            model_name='imagecompression',
            name='original_img',
            field=models.ImageField(upload_to='original_img/'),
        ),
    ]
